name: "Library Quality Check"
description: "Run library specific checks"
runs:
  using: 'composite'
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v2

    - name: "Setup Node.js"
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: "Install dependencies"
      run: npm install
      shell: bash

    - name: "Check lint (ESLint)"
      run: npm run eslint-check
      shell: bash

    - name: "Check code formatting (Prettier)"
      run: npm run prettier-check
      shell: bash

    - name: "Run tests"
      run: npm run unit 
      shell: bash
