name: "Demo Quality Checker"
description: "Check demo code quality"
runs:
  using: 'composite'
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v2

    - name: "Setup Node.js"
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: "Install dependencies"
      run: npm install

    - name: "Check lint (ESLint)"
      run: npm run eslint-check

    - name: "Check code formatting (Prettier)"
      run: npm run prettier-check

    - name: "Check lint (Stylelint)"
      run: npm run stylelint-check
